import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';

type PriorityLevel = 'High' | 'Medium' | 'Low';

type ActionPlanItem = {
  title: string;
  description: string;
  impact: PriorityLevel;
  effort: PriorityLevel;
};

const priorityOrder: Record<PriorityLevel, number> = {
  High: 0,
  Medium: 1,
  Low: 2,
};

const actionPlanItems: readonly ActionPlanItem[] = [
  {
    title: 'Fix landing page conversion leak',
    description: 'Tighten headline clarity and move proof higher so visitors see the value faster.',
    impact: 'High',
    effort: 'Low',
  },
  {
    title: 'Cut paid media waste',
    description:
      'Pause low-intent ad sets and shift budget toward campaigns with stronger trial quality.',
    impact: 'High',
    effort: 'Medium',
  },
  {
    title: 'Lift trial activation',
    description:
      'Shorten onboarding steps and surface the first success moment earlier in the flow.',
    impact: 'High',
    effort: 'Medium',
  },
  {
    title: 'Repair email drop-off',
    description:
      'Trim the nurture sequence and rewrite the weakest transition into the activation email.',
    impact: 'Medium',
    effort: 'Low',
  },
] as const;

function getImpactBadgeClassName(level: PriorityLevel): string {
  if (level === 'High') {
    return 'border-transparent bg-emerald-500/15 text-emerald-300';
  }

  if (level === 'Medium') {
    return 'border-transparent bg-amber-500/15 text-amber-300';
  }

  return 'border-transparent bg-slate-500/15 text-slate-300';
}

function getEffortBadgeClassName(level: PriorityLevel): string {
  if (level === 'High') {
    return 'border-transparent bg-rose-500/15 text-rose-300';
  }

  if (level === 'Medium') {
    return 'border-transparent bg-sky-500/15 text-sky-300';
  }

  return 'border-transparent bg-cyan-500/15 text-cyan-300';
}

export function ActionPlanList(): React.JSX.Element {
  const sortedItems = [...actionPlanItems].sort((left, right) => {
    const impactDifference = priorityOrder[left.impact] - priorityOrder[right.impact];

    if (impactDifference !== 0) {
      return impactDifference;
    }

    return priorityOrder[left.effort] - priorityOrder[right.effort];
  });

  return (
    <Card className='border-white/10 bg-white/5 text-white shadow-none'>
      <CardHeader className='space-y-3'>
        <div className='flex items-center justify-between gap-3'>
          <CardTitle className='text-base'>AI-Generated Action Plan</CardTitle>
          <Badge className='border-transparent bg-sky-500/15 text-sky-300'>Generated by AI</Badge>
        </div>
      </CardHeader>

      <CardContent className='space-y-3'>
        {sortedItems.map((item) => (
          <div
            key={item.title}
            className='space-y-3 rounded-2xl border border-white/10 bg-white/5 p-4'
          >
            <div className='flex items-start justify-between gap-3'>
              <p className='font-medium text-white'>{item.title}</p>
              <div className='flex shrink-0 items-center gap-2'>
                <Badge className={cn('whitespace-nowrap', getImpactBadgeClassName(item.impact))}>
                  {item.impact} impact
                </Badge>
                <Badge className={cn('whitespace-nowrap', getEffortBadgeClassName(item.effort))}>
                  {item.effort} effort
                </Badge>
              </div>
            </div>
            <p className='text-sm leading-6 text-slate-300'>{item.description}</p>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
